# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 13:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('refId', models.CharField(blank=True, max_length=40, null=True)),
                ('saleRefId', models.CharField(blank=True, max_length=40, null=True)),
                ('takingDate', models.DateTimeField(default=datetime.datetime.now)),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'کمک هزینه',
                'verbose_name_plural': 'کمک هزینه ها',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isopen', models.BooleanField(default=True)),
                ('payment_type', models.CharField(choices=[('heiat', 'هیئت'), ('mokeb', 'موکب')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfInstallment', models.IntegerField(default=1, null=True)),
                ('amount', models.IntegerField()),
                ('refId', models.CharField(blank=True, max_length=40, null=True)),
                ('saleRefId', models.CharField(blank=True, max_length=40, null=True)),
                ('takingDate', models.DateTimeField(default=datetime.datetime.now)),
                ('success', models.BooleanField(default=False)),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Registration')),
            ],
        ),
        migrations.AddField(
            model_name='charity',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.Expense'),
        ),
    ]
