# Generated by Django 3.0.3 on 2020-02-05 02:41

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
                ('expense_name', models.CharField(max_length=200)),
                ('callback_url', models.URLField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'درگاه',
                'verbose_name_plural': 'درگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfInstallment', models.IntegerField(default=1, null=True)),
                ('amount', models.IntegerField()),
                ('refId', models.CharField(blank=True, max_length=40, null=True)),
                ('saleRefId', models.CharField(blank=True, max_length=40, null=True)),
                ('takingDate', models.DateTimeField(default=datetime.datetime.now)),
                ('success', models.BooleanField(default=False)),
                ('expense',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments',
                                   to='pay.Expense')),
                ('registration',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments',
                                   to='program.Registration')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
    ]
