# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='expense',
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت ها'},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pay.Expense'),
        ),
        migrations.DeleteModel(
            name='Charity',
        ),
    ]
