# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='numberOfInstallment',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Registration'),
        ),
    ]
