# Generated by Django 2.0.13 on 2020-04-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='short_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='optional_mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='optional_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
