# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 06:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_auto_20160929_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('refId', models.CharField(blank=True, max_length=40, null=True)),
                ('saleRefId', models.CharField(blank=True, max_length=40, null=True)),
                ('takingDate', models.DateTimeField(default=datetime.datetime.now)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
    ]
