# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_auto_20161002_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='isopen',
            new_name='is_open',
        ),
    ]
