# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_charity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isopen', models.BooleanField(default=True)),
                ('payment_type', models.CharField(choices=[('heiat', 'هیئت'), ('mokeb', 'موکب')], max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='charity',
            name='expense',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pay.Expense'),
            preserve_default=False,
        ),
    ]
