# Generated by Django 2.0.13 on 2020-04-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_auto_20200416_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
