# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-13 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_auto_20161002_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='callback_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
