# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_auto_20160929_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charity',
            options={'verbose_name': 'کمک هزینه', 'verbose_name_plural': 'کمک هزینه ها'},
        ),
    ]
