# Generated by Django 2.0.8 on 2018-09-04 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0005_auto_20180903_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pay.Expense'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='program.Registration'),
        ),
    ]
