# Generated by Django 2.0.13 on 2020-05-21 23:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pay', '0006_auto_20200521_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='boolean_title',
            new_name='flag_title',
        ),
    ]
