# Generated by Django 3.0.3 on 2020-02-05 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('food', models.CharField(blank=True, max_length=100, null=True, verbose_name='غذا')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع توزیع')),
                ('end', models.DateTimeField(verbose_name='زمان پایان توزیع')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Program',
                                              verbose_name='برنامه')),
            ],
        ),
        migrations.CreateModel(
            name='FoodReception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(
                    choices=[('receipt', 'دریافت کرده'), ('cancel', 'لغو کرده'), ('reserved', 'رزرو کرده')],
                    max_length=20, verbose_name='وضعیت')),
                ('reception_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان دریافت')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dining.Meal',
                                           verbose_name='وعدهٔ غذایی')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile',
                                              verbose_name='کاربر')),
            ],
        ),
    ]
