# Generated by Django 2.0.13 on 2020-02-05 06:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='end',
            new_name='end_time',
        ),
    ]
