# Generated by Django 2.0.13 on 2020-02-08 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0003_auto_20200205_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodreception',
            options={'verbose_name': 'دیافت غذا', 'verbose_name_plural': 'دریافت\u200cهای غذا'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'وعدهٔ غذایی', 'verbose_name_plural': 'وعده\u200cهای غذایی'},
        ),
    ]
