# Generated by Django 2.0.13 on 2020-04-16 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dining', '0004_auto_20200208_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodreception',
            options={'verbose_name': 'دریافت غذا', 'verbose_name_plural': 'دریافت\u200cهای غذا'},
        ),
        migrations.AlterField(
            model_name='meal',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Program',
                                    verbose_name='برنامه'),
        ),
    ]
