# Generated by Django 3.0.3 on 2020-02-05 02:40

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='نام برنامه', max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('has_coupling', models.BooleanField(default=False)),
                ('program_interval', models.CharField(default='زمان برنامه', max_length=80)),
                ('register_interval', models.CharField(default='زمان ثبت نام', max_length=80)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(
                    choices=[('arbaeen', 'اربعین'), ('etekaf', 'اعتکاف'), ('mashhad', 'پابوس عشق'),
                             ('marasem', 'مراسم'), ('south', 'اردو جنوب'), ('voroodi', 'اردو ورودی ها'),
                             ('guest', 'سایر')], max_length=200)),
                ('base_price', models.IntegerField(default=0)),
                ('max_first_installment', models.IntegerField(default=10000000)),
                ('max_second_installment', models.IntegerField(default=10000000)),
                ('state',
                 models.CharField(choices=[('config', 'در حال پیکربندی'), ('active', 'فعال'), ('archive', 'بایگانی')],
                                  default='config', max_length=32)),
            ],
            options={
                'verbose_name': 'برنامه',
                'verbose_name_plural': 'برنامه ها',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationDate', models.DateTimeField(default=datetime.datetime.now)),
                ('coupling', models.BooleanField(default=False)),
                ('numberOfPayments', models.IntegerField(default=0)),
                ('status', models.CharField(
                    choices=[('default', 'منتظر قرعه کشی'), ('certain', 'قطعی'), ('reserved', 'رزرو'),
                             ('given up', 'انصراف'), ('removed', 'پاک شده'), ('suspended', 'معلق'),
                             ('not chosen', 'انتخاب نشده'), ('came', 'شرکت کرده'), ('not came', 'شرکت نکرده'),
                             ('temporary', 'موقت'), ('first stage', 'مرحله اول')], default='default', max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations',
                                              to='accounts.Profile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations',
                                              to='program.Program')),
            ],
            options={
                'verbose_name': 'ثبت نام',
                'verbose_name_plural': 'ثبت نام ها',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('desc', models.TextField(blank=True, null=True)),
                ('user_sees', models.BooleanField(default=False)),
                ('shift', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions',
                                              to='program.Program')),
            ],
        ),
        migrations.CreateModel(
            name='PriceShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_type', models.CharField(
                    choices=[('sharif student', 'دانشجو شریف'), ('sharif graduated', 'فارغ التحصیل شریف'),
                             ('sharif graduated talabe', 'فاغ التحصیل شریف و طلبه فعلی'),
                             ('sharif graduated student not sharif', 'فارغ التحصیل شریف و دانشجو سایر'),
                             ('not sharif student', 'دانشجو سایر'), ('not sharif graduated', 'فارغ التحصیل سایر'),
                             ('talabe', 'طلبه'), ('sharif master', 'استاد شریف'), ('sharif employed', 'کارمند شریف'),
                             ('other', 'سایر')], max_length=128)),
                ('shift', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts',
                                              to='program.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts',
                                              to='program.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('send_sms', models.BooleanField(default=False)),
                ('send_date', models.DateTimeField(default=datetime.datetime.now)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages',
                                                   to='program.Registration')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers',
                                               to='program.Question')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers',
                                                   to='program.Registration')),
            ],
        ),
    ]
