# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 13:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canEditProgram', models.BooleanField(default=False)),
                ('canFilter', models.BooleanField(default=False)),
                ('canSelect', models.BooleanField(default=False)),
                ('canEditRegistration', models.BooleanField(default=False)),
                ('canDocument', models.BooleanField(default=False)),
                ('canMessage', models.BooleanField(default=False)),
                ('canAdd', models.BooleanField(default=False)),
                ('documentation', models.CharField(blank=True, max_length=10000, null=True)),
                ('role', models.CharField(choices=[('master manager', 'مسئول برنامه'), ('vicar', 'جانشین'), ('registration manager', 'مسئول ثبت نام'), ('sisters manager', 'مسئول خواهران'), ('sister registration manager', 'مسئول ثبت نام خواهران'), ('communication sisters manager', 'مسئول ارتباط با خواهران'), ('logistic manager', 'مسئول تدارکات'), ('logistic crew', 'کادر تداراکات'), ('executive manager', 'مسئول اجرایی'), ('executive crew', 'کادر اجرایی'), ('pantry manager', 'مسئول آبدارخانه'), ('pantry crew', 'کادر آبدارخانه'), ('advertising manager', 'مسئول تبلیغات'), ('advertising crew', 'کادر تبلیغات'), ('crew', 'کادر'), ('kitchen manager', 'مسئول سلف'), ('kitchen vicar', 'معاون سلف'), ('kitchen crew', 'کادر سلف')], default='master manager', max_length=200)),
                ('comment', models.CharField(blank=True, max_length=800, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'مدیریت',
                'verbose_name_plural': 'مدیریت ها',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('sendEmail', models.BooleanField(default=False)),
                ('sendSms', models.BooleanField(default=False)),
                ('sendInbox', models.BooleanField(default=False)),
                ('messageSendDate', models.DateTimeField(default=datetime.datetime.now)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Management')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.CreateModel(
            name='Message_reciving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Message')),
            ],
            options={
                'verbose_name': 'دریافت پیام',
                'verbose_name_plural': 'دریافت پیام ها',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price1', models.IntegerField(blank=True, null=True)),
                ('price2', models.IntegerField(blank=True, null=True)),
                ('price3', models.IntegerField(blank=True, null=True)),
                ('coupling', models.BooleanField(default=False)),
                ('additionalOption', models.BooleanField(default=False)),
                ('people_type', models.CharField(choices=[('sharif student', 'دانشجو شریف'), ('sharif graduated', 'فارغ التحصیل شریف'), ('sharif graduated talabe', 'فاغ التحصیل شریف و طلبه فعلی'), ('sharif graduated student not sharif', 'فارغ التحصیل شریف و دانشجو سایر'), ('not sharif student', 'دانشجو سایر'), ('not sharif graduated', 'فارغ التحصیل سایر'), ('talabe', 'طلبه'), ('sharif master', 'استاد شریف'), ('sharif employed', 'کارمند شریف'), ('other', 'سایر')], max_length=200)),
            ],
            options={
                'verbose_name': 'قیمت',
                'verbose_name_plural': 'قیمت ها',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='نام برنامه', max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('isOpen', models.BooleanField(default=False)),
                ('additionalOption', models.CharField(blank=True, max_length=30, null=True)),
                ('hasCoupling', models.BooleanField(default=False)),
                ('isPublic', models.BooleanField(default=False)),
                ('programInterval', models.CharField(default='زمان برنامه', max_length=80)),
                ('registerInterval', models.CharField(default='زمان ثبت نام', max_length=80)),
                ('creationDate', models.DateTimeField(default=datetime.datetime.now)),
                ('notes', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('emailPassword', models.CharField(blank=True, max_length=200, null=True)),
                ('startDate', models.DateField(default=datetime.datetime.now)),
                ('type', models.CharField(choices=[('arbaeen', 'اربعین'), ('etekaf', 'اعتکاف'), ('mashhad', 'پابوس عشق')], max_length=200)),
            ],
            options={
                'verbose_name': 'برنامه',
                'verbose_name_plural': 'برنامه ها',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationDate', models.DateTimeField(default=datetime.datetime.now)),
                ('additionalOption', models.BooleanField(default=False)),
                ('label1', models.BooleanField(default=False)),
                ('label2', models.BooleanField(default=False)),
                ('label3', models.IntegerField(default=0)),
                ('label4', models.IntegerField(default=0)),
                ('coupling', models.BooleanField(default=False)),
                ('feedBack', models.CharField(blank=True, max_length=2000, null=True)),
                ('numberOfPayments', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('default', 'منتظر قرعه کشی'), ('certain', 'قطعی'), ('reserved', 'رزرو'), ('given up', 'انصراف'), ('removed', 'پاک شده'), ('suspended', 'معلق'), ('not chosen', 'انتخاب نشده'), ('came', 'شرکت کرده'), ('not came', 'شرکت نکرده'), ('temporary', 'موقت'), ('first stage', 'مرحله اول')], default='default', max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Program')),
            ],
            options={
                'verbose_name': 'ثبت نام',
                'verbose_name_plural': 'ثبت نام ها',
            },
        ),
        migrations.AddField(
            model_name='pricing',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Program'),
        ),
        migrations.AddField(
            model_name='message_reciving',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Registration'),
        ),
        migrations.AddField(
            model_name='management',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Program'),
        ),
    ]
