# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-05 17:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='startDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
