# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management',
            old_name='role_choices',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='people_type_choices',
            new_name='people_type',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='status_choices',
            new_name='status',
        ),
    ]
