# Generated by Django 2.0.13 on 2021-01-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_registration_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='var',
            field=models.CharField(choices=[('yesno', 'بله خیر'), ('multiple', 'چند گزینه ای'), ('file', 'فایل')], default='yesno', max_length=20),
        ),
    ]
