# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-05 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20161005_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='notes',
            field=models.CharField(max_length=20000),
        ),
    ]
