# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20160810_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='registration',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
