# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20160819_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='canAdd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='management',
            name='canDocument',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='management',
            name='canEditProgram',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='management',
            name='canEditRegistration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='management',
            name='canFilter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='management',
            name='canMassage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='management',
            name='canSelect',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='numberOfPayments',
            field=models.IntegerField(default=0),
        ),
    ]
