# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-07 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20161005_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.CharField(choices=[('arbaeen', 'اربعین'), ('etekaf', 'اعتکاف'), ('mashhad', 'پابوس عشق'), ('marasem', 'مراسم')], max_length=200),
        ),
    ]
