# Generated by Django 2.0.13 on 2021-01-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_question_var'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(null=True),
        ),
    ]
