# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20160819_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='numberOfPayments',
            field=models.IntegerField(default=1),
        ),
    ]
