# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-08 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20161007_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='management',
            options={'verbose_name': 'مسئولیت', 'verbose_name_plural': 'مسئولیت\u200cها'},
        ),
    ]
