# Generated by Django 2.0.13 on 2021-01-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_answer_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='params',
            field=models.TextField(blank=True, null=True),
        ),
    ]
