# Generated by Django 2.0.13 on 2021-01-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_question_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
