# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-03 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_auto_20161008_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.CharField(choices=[('arbaeen', 'اربعین'), ('etekaf', 'اعتکاف'), ('mashhad', 'پابوس عشق'), ('marasem', 'مراسم'), ('south', 'اردو جنوب'), ('voroodi', 'اردو ورودی ها'), ('guest', 'سایر')], max_length=200),
        ),
    ]
