# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_auto_20160820_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='additionalObject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='additionalObject',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='additionalObject',
            field=models.BooleanField(default=False),
        ),
    ]
