# Generated by Django 2.0.13 on 2021-01-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_answer_answer_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
