# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_auto_20160821_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='numberOfPayments',
            field=models.IntegerField(default=0),
        ),
    ]
