# Generated by Django 2.0.13 on 2021-01-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_auto_20210130_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='default_status',
            field=models.CharField(choices=[('default', 'منتظر قرعه کشی'), ('certain', 'قطعی'), ('reserved', 'رزرو'), ('given up', 'انصراف'), ('removed', 'پاک شده'), ('suspended', 'معلق'), ('not chosen', 'انتخاب نشده'), ('came', 'شرکت کرده'), ('not came', 'شرکت نکرده'), ('temporary', 'موقت'), ('first stage', 'مرحله اول')], default='default', max_length=200),
        ),
    ]
