# Generated by Django 2.0.13 on 2021-01-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_program_default_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='donate_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='donate_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
