# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-04 05:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_message2'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='state',
            field=models.CharField(choices=[('config', 'در حال پیکربندی'), ('active', 'فعال'), ('archive', 'بایگانی')], default='config', max_length=32),
        ),
        migrations.AlterField(
            model_name='message2',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
