# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-28 07:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_program_emailpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='Coupling',
            new_name='coupling',
        ),
        migrations.AddField(
            model_name='program',
            name='startDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
