# Generated by Django 2.0.8 on 2018-09-04 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_auto_20180904_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message_reciving',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message_reciving',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='program',
        ),
        migrations.AlterField(
            model_name='management',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managements', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='management',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managements', to='program.Program'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='program.Program'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Message_reciving',
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
