# Generated by Django 2.0.8 on 2018-09-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_auto_20180904_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='email',
        ),
        migrations.RemoveField(
            model_name='program',
            name='emailPassword',
        ),
        migrations.RemoveField(
            model_name='program',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='program',
            name='startDate',
        ),
    ]
