# Generated by Django 2.0.8 on 2018-09-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0016_auto_20180904_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message2',
            new_name='Message',
        ),
        migrations.RemoveField(
            model_name='management',
            name='canDocument',
        ),
    ]
