# Generated by Django 2.0.8 on 2018-09-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0017_auto_20180904_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='base_price',
            field=models.IntegerField(default=0),
        ),
    ]
