# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0017_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='management',
            options={'verbose_name': 'مدیریت', 'verbose_name_plural': 'مدیریت ها'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام ها'},
        ),
        migrations.AlterModelOptions(
            name='message_reciving',
            options={'verbose_name': 'دریافت پیام', 'verbose_name_plural': 'دریافت پیام ها'},
        ),
        migrations.AlterModelOptions(
            name='pricing',
            options={'verbose_name': 'قیمت', 'verbose_name_plural': 'قیمت ها'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'برنامه', 'verbose_name_plural': 'برنامه ها'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'ثبت نام', 'verbose_name_plural': 'ثبت نام ها'},
        ),
    ]
