# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 13:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mugshot', models.CharField(max_length=50, verbose_name='mugshot')),
                ('privacy', models.CharField(choices=[('open', 'Open'), ('registered', 'Registered'), ('closed', 'Closed')], default='registered', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy')),
                ('entranceDate', models.DateTimeField(default=datetime.datetime.now, max_length=20)),
                ('melliCode', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('gender', models.BooleanField(default=1)),
                ('address', models.CharField(max_length=400)),
                ('shenasname', models.CharField(max_length=11)),
                ('studentNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('fatherName', models.CharField(max_length=200)),
                ('cellPhone', models.CharField(max_length=11)),
                ('emergencyPhone', models.CharField(blank=True, max_length=20, null=True)),
                ('conscriptionDesc', models.CharField(blank=True, max_length=200, null=True)),
                ('deActivated', models.BooleanField(default=False)),
                ('birthYear', models.IntegerField(null=True)),
                ('birthMonth', models.IntegerField(null=True)),
                ('birthDay', models.IntegerField(null=True)),
                ('people_type', models.CharField(choices=[('sharif student', 'دانشجو شریف'), ('sharif graduated', 'فارغ التحصیل شریف'), ('sharif graduated talabe', 'فاغ التحصیل شریف و طلبه فعلی'), ('sharif graduated student not sharif', 'فارغ التحصیل شریف و دانشجو سایر'), ('not sharif student', 'دانشجو سایر'), ('not sharif graduated', 'فارغ التحصیل سایر'), ('talabe', 'طلبه'), ('sharif master', 'استاد شریف'), ('sharif employed', 'کارمند شریف'), ('other', 'سایر')], max_length=200)),
                ('conscription', models.CharField(choices=[('went', 'دارای کارت پایان خدمت'), ('exempt', 'معافیت دایم '), ('educational exempt', 'معافیت تحصیلی'), ('other', 'سایر')], max_length=200)),
                ('passport', models.CharField(choices=[('have', 'دارم'), ('not have', 'ندارم')], max_length=200, null=True)),
                ('passport_number', models.IntegerField(blank=True, null=True)),
                ('passport_dateofissue', models.DateField(blank=True, null=True)),
                ('passport_dateofexpiry', models.DateField(blank=True, null=True)),
                ('couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'حساب کاربری',
                'verbose_name_plural': 'حسابهای کاربری',
            },
        ),
    ]
