# Generated by Django 3.0.3 on 2020-02-05 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_type', models.CharField(
                    choices=[('sharif student', 'دانشجو شریف'), ('sharif graduated', 'فارغ التحصیل شریف'),
                             ('sharif graduated talabe', 'فاغ التحصیل شریف و طلبه فعلی'),
                             ('sharif graduated student not sharif', 'فارغ التحصیل شریف و دانشجو سایر'),
                             ('not sharif student', 'دانشجو سایر'), ('not sharif graduated', 'فارغ التحصیل سایر'),
                             ('talabe', 'طلبه'), ('sharif master', 'استاد شریف'), ('sharif employed', 'کارمند شریف'),
                             ('other', 'سایر')], default='other', max_length=200, verbose_name='وضعیت تحصیل')),
                ('student_number',
                 models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره دانشجویی')),
                ('gender',
                 models.BooleanField(choices=[(True, 'مرد'), (False, 'زن')], default=True, verbose_name='جنسیت')),
                ('father_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام پدر')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره موبایل')),
                ('passport',
                 models.CharField(blank=True, choices=[('have', 'دارم'), ('not have', 'ندارم')], max_length=200,
                                  null=True, verbose_name='وضعیت گذرنامه')),
                ('passport_number',
                 models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره گذرنامه')),
                ('passport_date_of_issue',
                 models.DateField(blank=True, null=True, verbose_name='تاریخ صدور گذرنامه به میلادی')),
                ('passport_date_of_expiry',
                 models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا گذرنامه به میلادی')),
                ('conscription', models.CharField(blank=True, choices=[('went', 'دارای کارت پایان خدمت'),
                                                                       ('exempt', 'معافیت دایم '),
                                                                       ('educational exempt', 'معافیت تحصیلی'),
                                                                       ('army', 'نظامی'),
                                                                       ('without_condition', 'غیر مشمول'),
                                                                       ('respite', 'مهلت قانونی معرفی'),
                                                                       ('other', 'سایر')], max_length=200, null=True,
                                                  verbose_name='وضعیت نظام وظیفه')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             to='accounts.Profile', verbose_name='همسر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile',
                                              to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'حساب کاربری',
                'verbose_name_plural': 'حسابهای کاربری',
            },
        ),
    ]
