# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 10:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entranceDate', models.DateTimeField(default=datetime.datetime.now, max_length=20)),
                ('melliCode', models.CharField(max_length=10)),
                ('gender', models.BooleanField(default=1)),
                ('coupling', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('shenasname', models.CharField(blank=True, max_length=11, null=True)),
                ('studentNumber', models.IntegerField(blank=True, null=True)),
                ('fatherName', models.CharField(blank=True, max_length=200, null=True)),
                ('cellPhone', models.CharField(max_length=11)),
                ('emergencyPhone', models.CharField(blank=True, max_length=20, null=True)),
                ('conscriptionDesc', models.CharField(blank=True, max_length=200, null=True)),
                ('deActivated', models.BooleanField(default=False)),
                ('birthYear', models.IntegerField(null=True)),
                ('birthMonth', models.IntegerField(null=True)),
                ('birthDay', models.IntegerField(null=True)),
                ('people_type_choices', models.CharField(choices=[('sharif student', 'دانشجو شریف'), ('sharif graduated', 'فارغ التحصیل شریف'), ('sharif graduated talabe', 'فاغ التحصیل شریف و طلبه فعلی'), ('sharif graduated student not sharif', 'فارغ التحصیل شریف و دانشجو سایر'), ('not sharif student', 'دانشجو سایر'), ('not sharif graduated', 'فارغ التحصیل سایر'), ('talabe', 'طلبه'), ('sharif master', 'استاد شریف'), ('sharif employed', 'کارمند شریف'), ('other', 'سایر')], max_length=200)),
                ('conscription_choices', models.CharField(choices=[('went', 'دارای کارت پایان خدمت'), ('exempt', 'معافیت دایم '), ('educational exempt', 'معافیت تحصیلی'), ('other', 'سایر')], max_length=200)),
                ('passport_choices', models.CharField(choices=[('have', 'دارم'), ('have 7', 'دارم ولی کمتر از 7 ماه انقضا دارد '), ('not have', 'ندارم')], default='have 7', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
