# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='conscription_choices',
            new_name='conscription',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='passport_choices',
            new_name='passport',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='people_type_choices',
            new_name='people_type',
        ),
    ]
