# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161003_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='melliCode',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(choices=[(True, 'مرد'), (False, 'زن')], default=True),
        ),
    ]
