# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160819_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coupling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
