# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-05 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20161003_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='studentNumber',
            field=models.CharField(max_length=20, null=True, verbose_name='شماره دانشجویی'),
        ),
    ]
