# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20160824_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coupling',
            field=models.BooleanField(default=1),
        ),
    ]
