# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_coupling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='coupling',
        ),
    ]
