# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-04 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='conscription',
            field=models.CharField(choices=[('went', 'دارای کارت پایان خدمت'), ('exempt', 'معافیت دایم '), ('educational exempt', 'معافیت تحصیلی'), ('army', 'نظامی'), ('without_condition', 'غیر مشمول'), ('respite', 'مهلت قانونی معرفی'), ('other', 'سایر')], max_length=200, verbose_name='وضعیت نظام وظیفه'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
