# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20160829_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='conscription',
            field=models.CharField(choices=[('went', 'دارای کارت پایان خدمت'), ('exempt', 'معافیت دایم '), ('educational exempt', 'معافیت تحصیلی'), ('other', 'سایر')], max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport',
            field=models.CharField(choices=[('have', 'دارم'), ('not have', 'ندارم')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='people_type',
            field=models.CharField(choices=[('sharif student', 'دانشجو شریف'), ('sharif graduated', 'فارغ التحصیل شریف'), ('sharif graduated talabe', 'فاغ التحصیل شریف و طلبه فعلی'), ('sharif graduated student not sharif', 'فارغ التحصیل شریف و دانشجو سایر'), ('not sharif student', 'دانشجو سایر'), ('not sharif graduated', 'فارغ التحصیل سایر'), ('talabe', 'طلبه'), ('sharif master', 'استاد شریف'), ('sharif employed', 'کارمند شریف'), ('other', 'سایر')], max_length=200),
        ),
    ]
