# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-04 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180904_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='studentNumber',
            new_name='student_number',
        ),
    ]
