# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20160829_0908'),
        ('accounts', '0014_auto_20160829_0933'),
    ]

    operations = [
    ]
