# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-04 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180904_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fatherName',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='cellPhone',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shenasname',
        ),
    ]
