# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import userena.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=userena.models.UserenaBaseProfile),
        ),
    ]
