# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-04 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180904_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='passport_dateofexpiry',
            new_name='passport_date_of_expiry',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='passport_dateofissue',
            new_name='passport_date_of_issue',
        ),
    ]
