# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20160905_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='azzahra/static/profile'),
        ),
    ]
