# Generated by Django 2.0.8 on 2018-09-04 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180904_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='couple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile', verbose_name='همسر'),
        ),
    ]
