# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20160905_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='/static/profile/'),
        ),
    ]
