# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20160905_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
