# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20160905_1538'),
        ('accounts', '0024_auto_20160905_2133'),
    ]

    operations = [
    ]
