# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 11:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_dateofexpiry',
            field=models.DateField(default=datetime.datetime(2016, 9, 14, 10, 59, 44, 566836, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_dateofissue',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_number',
            field=models.IntegerField(),
        ),
    ]
