# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20160914_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='passport_dateofexpiry',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_dateofissue',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_number',
            field=models.IntegerField(null=True),
        ),
    ]
