# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20160914_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'حساب کاربری', 'verbose_name_plural': 'حسابهای کاربری'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fatherName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='melliCode',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_dateofexpiry',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_dateofissue',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shenasname',
            field=models.CharField(max_length=11),
        ),
    ]
