# Generated by Django 2.0.8 on 2018-09-18 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0019_auto_20180918_1125'),
        ('accounts', '0021_auto_20180904_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canEditProgram', models.BooleanField(default=False)),
                ('canFilter', models.BooleanField(default=False)),
                ('canSelect', models.BooleanField(default=False)),
                ('canEditRegistration', models.BooleanField(default=False)),
                ('canMessage', models.BooleanField(default=False)),
                ('canAdd', models.BooleanField(default=False)),
                ('documentation', models.CharField(blank=True, max_length=10000, null=True)),
                ('role', models.CharField(choices=[('master manager', 'مسئول برنامه'), ('vicar', 'جانشین'), ('registration manager', 'مسئول ثبت نام'), ('sisters manager', 'مسئول خواهران'), ('sister registration manager', 'مسئول ثبت نام خواهران'), ('communication sisters manager', 'مسئول ارتباط با خواهران'), ('logistic manager', 'مسئول تدارکات'), ('logistic crew', 'کادر تداراکات'), ('executive manager', 'مسئول اجرایی'), ('executive crew', 'کادر اجرایی'), ('pantry manager', 'مسئول آبدارخانه'), ('pantry crew', 'کادر آبدارخانه'), ('advertising manager', 'مسئول تبلیغات'), ('advertising crew', 'کادر تبلیغات'), ('crew', 'کادر'), ('kitchen manager', 'مسئول سلف'), ('kitchen vicar', 'معاون سلف'), ('kitchen crew', 'کادر سلف')], default='master manager', max_length=200)),
                ('comment', models.CharField(blank=True, max_length=800, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managements', to='accounts.Profile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managements', to='program.Program')),
            ],
            options={
                'verbose_name': 'مسئولیت',
                'verbose_name_plural': 'مسئولیت\u200cها',
            },
        ),
    ]
